apiVersion: v1
kind: Service
metadata:
  name: {{ include "zabbix-server-mysql.fullname" . }}
  labels:
    {{- include "zabbix-server-mysql.labels" . | nindent 4 }}    
spec:
  type: {{ .Values.service.server.type }} 
  selector:
    {{- include "zabbix-server-mysql.selectorLabels" . | nindent 4 }}
  #clusterIP: None
  ports:
  - name: 10051-tcp
    port: {{ .Values.service.server.port }} 
    protocol: TCP
    targetPort: {{ .Values.service.server.port }}
  - name: snmp-trap
    port: 162
    protocol: UDP
    targetPort: 162
  externalIPs:
  - {{ .Values.service.server.externalIP }}
#  loadBalancerIP: {{ .Values.service.server.loadBalancerIP }}
