apiVersion: v1
kind: Service
metadata:
  name: {{ include "zabbix-server-mysql.fullname" . }}-web
  labels:
    {{- include "zabbix-server-mysql.labels" . | nindent 4 }}-web    
spec:
  type: {{ .Values.service.web.type }} 
  selector:
    {{- include "zabbix-server-mysql.selectorLabels" . | nindent 4 }}-web
  ports:
  - name: http-tcp
    port: {{ .Values.service.web.http_port }}
    protocol: TCP
    targetPort: {{ .Values.service.web.http_port }}
  - name: 443-tcp
    port: {{ .Values.service.web.https_port }}
    protocol: TCP
    targetPort: {{ .Values.service.web.https_port }} 
  loadBalancerIP: {{ .Values.service.web.loadBalancerIP }}
